#!/bin/sh
# one-time system initialization

PATH=/bin:/sbin:/usr/bin:/usr/sbin
trap : INT
trap : QUIT

sh /etc/rc autoboot
if test $? -ne 0; then
  # /etc/rc crashed, start emergency shell.
  echo '/etc/rc failed. Press <enter> for emergency shell...'
  read input
  sh -p
  exec reboot
fi
touch /etc/runit/stopit
chmod 0 /etc/runit/stopit
