.Dd $Mdocdate$
.Dt SF 8
.Os
.Sh NAME
.Nm sf
.Nd service framework
.Sh SYNOPSIS
.Nm sf
.Op start|stop|restart
.Sh DESCRIPTION
.Nm
is an init scheme that uses runit's
.Xr runsv 8
to run daemons.
.Sh FILES
blah blah
.Sh EXAMPLES
blah blah
.Sh SEE ALSO
.Xr sh 1
.Sh HISTORY
.Nm
was inspired by the NetBSD init scheme.
