#!/bin/mksh
# vim: syntax=sh

. /etc/sf.subr

log () {
	print -ru2 "$*"
}

if [ $# -ne 2 ]; then
	log 'wrong number of args: expected 2'
	exit 1
fi

case $1 in
	status)
		x=`sv status /libexec/sf.d/$2`
		if [ $? -eq 0 ]; then
			log "$x"
		else
			log 'not running'
		fi
		;;
	*)
		log "$1 unimplemented"
		;;
esac
