#!/bin/mksh
# vim: syntax=sh

if mountpoint -q /dev; then
	:
else
	mount -t proc  proc /proc
	mount -t sysfs sys  /sys
	mount -t devtmpfs devtmpfs /dev
	mkdir /dev/pts
	mount -t devpts devpts /dev/pts
	mount -t tmpfs tmpfs /tmp
	mount -o remount,rw /

	printf -- "boot took $(cut -d' ' -f1 /proc/uptime) secs\n"
fi

cat <<EOF

+------------------------------+
|  welcome to multiuser mode!  |
+------------------------------+

EOF

PATH=/usr/local/bin:/usr/local/sbin
PATH=${PATH}:/usr/bin:/usr/sbin
PATH=${PATH}:/bin:/sbin
export PATH

# ignore signals, so we don't die to halt/poweroff/reboot sending us
# TERM or HUP
trap '' INT HUP TERM

while :; do
	print 'new shell:'
	PS1='$(pwd) # ' /bin/mksh
done
